// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesTracker_RJLOZANSKI.Models;

#nullable disable

namespace SalesTracker_RJLOZANSKI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211052240_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("SalesTracker_RJLOZANSKI.Models.Deal", b =>
                {
                    b.Property<int>("DealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CloseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DealValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("SalesRepID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DealID");

                    b.HasIndex("SalesRepID");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("SalesTracker_RJLOZANSKI.Models.SalesRep", b =>
                {
                    b.Property<int>("SalesRepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthQuota")
                        .HasColumnType("TEXT");

                    b.Property<string>("Territory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SalesRepID");

                    b.ToTable("SalesReps");
                });

            modelBuilder.Entity("SalesTracker_RJLOZANSKI.Models.Deal", b =>
                {
                    b.HasOne("SalesTracker_RJLOZANSKI.Models.SalesRep", "SalesRep")
                        .WithMany("Deals")
                        .HasForeignKey("SalesRepID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesRep");
                });

            modelBuilder.Entity("SalesTracker_RJLOZANSKI.Models.SalesRep", b =>
                {
                    b.Navigation("Deals");
                });
#pragma warning restore 612, 618
        }
    }
}
